server:
  port: 8002
spring:
  application:
    name: storage-service # 库存微服务模块
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_storage?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#    alibaba:
#      seata:
#        # (order,storage,account)事务组名称，与seata配置文件中vgroup_mapping.storage_group值一致
#        tx-service-group: storage_group

# 使用yaml配置 seata conf配置文件 -----start----|
seata:
  client:
    support:
      spring:
        datasource-autoproxy: true # 数据源自动代理 默认 true
  registry:
    nacos:
      server-addr: localhost:8848
      namespace: ""
      cluster: default
  tx-service-group: storage_group
  service:
    vgroup-mapping: default
    grouplist: 127.0.0.1:8091
    enable-degrade: false
#    disable-global-transaction: false # 默认 false
# 使用yaml配置 seata conf配置文件 -----end-----|



mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.hyd.work.entity

logging:
  level:
    io:
      seata: debug