server:
  port: 8001
spring:
  application:
    name: cloud-provider-sleuth-payment8001
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1 # 采样率值介于 0 到 1 之间，1 则表示全部采集
eureka:
  instance:
    appname: cloud-provider-sleuth-payment-service
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka # 单机版