server:
  port: 3344
spring:
  application:
    name: cloud-config-center3344
  cloud:
    config:
      server:
        git:
          uri: git@github.com:ayiyaha-hyd/spring-cloud-config.git
          search-paths: # 搜索目录
            - spring-cloud-config
      label: master # 读取分支
  # rabbitmq相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address} # Eureka上显示的主机名
    appname: cloud-config-service # Eureka上显示的服务名
  client:
    service-url:
      defaultZone: http://cloud-eureka-server7001:7001/eureka/, http://cloud-eureka-server7002:7002/eureka/, http://cloud-eureka-server7003:7003/eureka/ #集群版
# rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
